STATE_FILES_DIRNAME = 'state_files'
STORE_FILENAME = f'{STATE_FILES_DIRNAME}/store.pickle'
SEQUENTIAL_SAVE_FILENAME = f'{STATE_FILES_DIRNAME}/sequential_save.txt'
USERS_JSON_FILENAME = f'{STATE_FILES_DIRNAME}/users.json'
